---
title: Jekyll Banking
timezone: UTC
collections:
  datafiles:
    title: Data
    output: false
  events:
    title: Events
    output: false
  feedback:
    title: Feedback
    output: false
  posts:
    title: Posts
    output: true
  services:
    title: Services
    output: true
  uploads:
    title: Uploads
    output: true
baseurl: "/jekyll-banking"
nav-key: nav
welcome-key: welcome
banner-key: banner
about-key: about
services-key: services
blog-key: blog
events-key: events
feedback-key: feedback
contact-key: contact
copyright-key: copyright